### ISSUE TITLE
Add functionality for relative Required Profile paths

### ISSUE THREAD

**Issue by jyundt** [DMTF/Redfish-Interop-Validator#142]
Following up on this [forum discussion](https://redfishforum.com/thread/583/required-profiles?page=1&scrollTo=2196), can "relative" path functionality be added to the Interop Validator?

As an example, given the following profile snippets that are located in the same directory / path:

`Base.v0_0_1.json`
```
{
        "SchemaDefinition": "RedfishInteroperabilityProfile.v1_5_0",
        "ProfileName": "Base",
        "ProfileVersion": "0.0.1",
        "Purpose": "Base Interop profile",
        "RequiredProfiles":{
                "DOBaseSystem": {
                        "MinVersion": "0.0.1",
                        
                }
        }
}
```

`DOBaseSystem.v0_0_1.json`
```
{
        "SchemaDefinition": "RedfishInteroperabilityProfile.v1_5_0",
        "ProfileName": "BaseSystem",
        "ProfileVersion": "0.0.1",
        "Protocol": {
                "MinVersion": "1.5",
                "Discovery": "None",
                "HostInterface": "Mandatory",
                "ExpandQuery": "Recommended",
                "FilterQuery": "Recommended",
                "SelectQuery": "Recommended",
                "OnlyQuery": "Recommended",
                "ExcerptQuery": "Recommended"
        },
        "Resources": {
                "ComputerSystemCollection":{
                        "PropertyRequirements":{
                                "Members":{
                                        "MinCount": 1
                                }
                        }
                }
        },
        "Registries": {}
}
```

I would like to be able to run the following command and have the Required Profiles files/paths correctly resolved:
```
# RedfishInteropValidator.py  --authtype Session -i https://192.168.0.100 -u root -p hunter2 /path/to/Base.v0_0_1.json
```

**Comment by tomasg2012** [comment]
Please check the branch `interop-dirpath` and check if it works with your issue.

**Comment by jyundt** [comment]
> Please check the branch `interop-dirpath` and check if it works with your issue.

Is there a missing `common/helper.py` file by any chance? I'm getting the following error when running the `interop-dirpath` branch:
```
Traceback (most recent call last):
  File "./RedfishInteropValidator.py", line 280, in <module>
    status_code, lastResultsPage, exit_string = main()
  File "./RedfishInteropValidator.py", line 138, in main
    from common.profile import getProfiles, checkProfileAgainstSchema, hashProfile
  File "/home/jyundt/git/Redfish-Interop-Validator/common/profile.py", line 13, in <module>
    from common.helper import splitVersionString, versionpattern
ModuleNotFoundError: No module named 'common.helper'
```

**Comment by tomasg2012** [comment]
Accidentally used the wrong filename, give it a try now.

**Comment by jyundt** [comment]
Looks good, thank you!
