### ISSUE TITLE
Run scripts will pop "not enough values to unpack"

### ISSUE THREAD

**Issue by RainHsieh** [DMTF/Redfish-Interop-Validator#194]
When run scripts will pop below error

Tool version: 2.1.7
Command Execute:python3 RedfishInteropValidator.py OCPBaselineHardwareManagement.v1_0_1.json -c config/test.ini -v
Error:
Program finished prematurely: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "RedfishInteropValidator.py", line 10, in <module>
    status_code, lastResultsPage, exit_string = main()
  File "/root/Desktop/Redfish/Redfish-Interop-Validator/redfish_interop_validator/RedfishInteropValidator.py", line 199, in main
    pmode, ppath = args.payload
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "RedfishInteropValidator.py", line 10, in <module>
    status_code, lastResultsPage, exit_string = main()
  File "/root/Desktop/Redfish/Redfish-Interop-Validator/redfish_interop_validator/RedfishInteropValidator.py", line 199, in main
    pmode, ppath = args.payload
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by RainHsieh** [comment]
fix
