### ISSUE TITLE
KeyError: 'Protocol' when running Redfish Interop Validator with OCPBasicServer profile

### ISSUE THREAD

**Issue by hcleepinga** [DMTF/Redfish-Interop-Validator#31]
I ran redfish interop validator with Open Compute Project profiles: OCPBasicServer and OCPManagedDevice. The error message  "KeyError: 'Protocol'" pops up when I ran with OCPBasicServer profile, but not with OCPManagedDevice profile.

Full error msg:

```
C:\Users\leejenn1\work\Redfish\Redfish-Interop-Validator-master>python RedfishInteropValidator.py -c config\config.ini profiles\OCPBasicServer.v1_0.json
CacheMode or path invalid, defaulting to Off
ConfigURI: https:// [deleted]
System Info: Test Config, place your own description of target system here
authtype: Basic,  cachefilepath: None,  cachemode: Off,  certificatebundle: None,  certificatecheck: False,  httpproxy: None,
httpsproxy: None,  localonlymode: False,  logpath: ./logs,  metadatafilepath: ./SchemaFiles/metadata,  payloadfilepath: None,  payloadmode: Default,
schemasuffix: _v1.xml,  servicemode: False,  timeout: 30,  username: root,  usessl: True,  warnrecommended: False,

Start time: 03/08/18 - 10:46:19
Traceback (most recent call last):
  File "RedfishInteropValidator.py", line 977, in <module>
    sys.exit(main(sys.argv))
  File "RedfishInteropValidator.py", line 854, in main
    success, counts, results, xlinks, topobj = validateURITree('/redfish/v1', 'ServiceRoot', profile, expectedJson=jsonData)
  File "RedfishInteropValidator.py", line 632, in validateURITree
    serviceVersion = profile["Protocol"].get('MinVersion', '1.0.0')
KeyError: 'Protocol'

```

The profiles can be downloaded here:
http://opencompute.org/wiki/Hardware_Management/SpecsAndDesigns#Baseline_and_Server_profile

**Comment by mraineri** [comment]
Fixed in PR #32
