### ISSUE TITLE
The RequiredProfiles property is not supported

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/Redfish-Interop-Validator#37]
A profile can extend another profile by using the RequiredProfiles property
```
	"RequiredProfiles": {
		"OCPBaselineHardwareManagement": {
			"MinVersion": "1.0.0"
		}
	},
```
The validator should read each referenced profile and tests for the requirements specified in the listed profile(s).

However, the validator appears to ignore this property.

**Comment by jcleung5549** [comment]
Reproduce using OCPServerHardware profile, who's RequiredProfiles references OCPBaselineHardware profile.

```
Using the latest OCPServerHardware profile, I still get the same “Protocol” keyword error:
Start time: 05/21/18 - 10:41:34
Traceback (most recent call last):
  File "C:\Users\...\work\Redfish\Redfish-Interop-Validator-master\RedfishInteropValidator.py", line 977, in <module>
    sys.exit(main(sys.argv))
  File "C:\Users\...\work\Redfish\Redfish-Interop-Validator-master\RedfishInteropValidator.py", line 854, in main
    success, counts, results, xlinks, topobj = validateURITree('/redfish/v1', 'ServiceRoot', profile, expectedJson=jsonData)
  File "C:\Users\...\work\Redfish\Redfish-Interop-Validator-master\RedfishInteropValidator.py", line 632, in validateURITree
    serviceVersion = profile["Protocol"].get('MinVersion', '1.0.0')
KeyError: 'Protocol'
```

**Comment by tomasg2012** [comment]
It just occurred to me, how is the program supposed to find the profile?  Is the RequiredProfile entry the same as the file name or some attribute inside the profile?

**Comment by mraineri** [comment]
Yes, we do have normative language about how the file names are used for profiles. So, based off the given name and version, you can construct the file name.

**Comment by mraineri** [comment]
This is the spec language for it:

> The JSON document describing a Profile follows the Redfish Schema file naming conventions from the Redfish Specification. The filename format for Profiles shall be formatted as:
**_ProfileName.vMajorVersion_MinorVersion_Errata.json_**
For example, version 1.2.0 of the BasicServer profile would be named "BasicServer.v1_2_0.json". The filename shall include the Profile name and Profile version matching those property values within the document.

**Comment by tomasg2012** [comment]
Now I guess my other question would be, does the program validate against both in one log?  I've been wondering how to combine the efforts.

**Comment by mraineri** [comment]
Yes, I would imagine it would pull in the required profiles and glue them together to create a single set of requirements, and generate a single log.

**Comment by jcleung5549** [comment]
I concur with having a single log.

**Comment by jcleung5549** [comment]
The OCP Profiles can be used to test this fix.  In the following site, the OCP Server Profile references the OCP Baseline Profile.

http://www.opencompute.org/wiki/Hardware_Management/SpecsAndDesigns
(OCP Profile section).

**Comment by hcleepinga** [comment]
I ran the tool from the branch you gave me, with OCPServer profile v0.2.3. It doesn’t complain about the key error : profile anymore, but it seems to me that the tool tried to pull in OCPBasic profile v1.0.0.
I am not sure if this is intended or a bug.
Here is the beginning of the log:
```
…
INFO - authtype: Basic,  cachefilepath: None,  cachemode: Off,  certificatebundle: None,  certificatecheck: False,  httpproxy: None,  
httpsproxy: None,  localonlymode: False,  logpath: ./logs,  metadatafilepath: ./SchemaFiles/metadata,  payloadfilepath: None,  payloadmode: Default,  
schemasuffix: _v1.xml,  servicemode: False,  timeout: 30,  username: root,  usessl: True,  warnrecommended: False,  

INFO - Start time: 06/21/18 - 14:59:38
DEBUG - callingResourceURI out of service with authtype Basic and ssl True: http://redfish.dmtf.org/profiles/OCPBaselineHardwareManagement.v1_0_0.json
ERROR - ConnectionError on http://redfish.dmtf.org/profiles/OCPBaselineHardwareManagement.v1_0_0.json
DEBUG - output: 
Traceback (most recent call last):
  File "C:\Users\leejenn1\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Users\leejenn1\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "C:\Users\leejenn1\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
…

```

The other thing is that I noticed the “ProfileVersion” in OCPBaselineHardwareManagement.v0_2_1.json is “1.0.0”, instead of “0.2.1”. Meanwhile OCPServerHardwareManagement.v0_2_3.json is with “ProfileVersion” “0.2.3”.

**Comment by hcleepinga** [comment]
Here is the command I issued:

`RedfishInteropValidator.py -c config\config.ini profiles\OCPServerHardwareManagement.v0_2_3.json`

And here is the setting in config.ini :

```
[SystemInformation]
TargetIP = xx.xx.xx.xx
SystemInfo = Test Config, place your own description of target system here
UserName = root
Password = two
AuthType = Basic
UseSSL = True
CertificateCheck = Off
CertificateBundle = 

[Options]
MetadataFilePath = ./SchemaFiles
CacheMode = Off
CacheFilePath =
SchemaSuffix = _v1.xml
Timeout = 30
HttpProxy =
HttpsProxy =
LocalOnlyMode = False
ServiceMode = False

[Validator]
PayloadMode = Default
PayloadFilePath = 
LogPath = ./logs 
WarnRecommended = False

```

**Comment by jcleung5549** [comment]
Posting report from additional testing...

The tool seems to be working with local only setting AND changing profile file name to OCPBaselineHardwareManagement.v1.0.0.json. Here is the detail description of my test:

```
LocalOnlyMode = True
ServiceMode = True
```
(supposedly they equal the option –service and –localonly in command line)
in config.ini file, put the 2 OCP profiles in the same folder as RedfishInteropValidator.py, and tried again.
The log still shows it looks for local copy of OCPBaselineHardwareManagement.v1_0_0.json but couldn’t find the profile:

```
C:\Users\leejenn1\work\Redfish\Redfish-Interop-Validator-required-profiles>RedfishInteropValidator.py -c config\config.ini OCPServerHardwareManagement.v0_2_3.json
CacheMode or path invalid, defaulting to Off
ConfigURI: https://10.243.48.65
System Info: Test Config, place your own description of target system here
authtype: Basic,  cachefilepath: None,  cachemode: Off,  certificatebundle: None,  certificatecheck: False,  httpproxy: None,
httpsproxy: None,  localonlymode: True,  logpath: ./logs,  metadatafilepath: ./SchemaFiles,  payloadfilepath: None,  payloadmode: Default,
schemasuffix: _v1.xml,  servicemode: True,  timeout: 30,  username: root,  usessl: True,  warnrecommended: False,

Start time: 06/25/18 - 14:34:32
Traceback (most recent call last):
  File "C:\Users\leejenn1\work\Redfish\Redfish-Interop-Validator-required-profiles\RedfishInteropValidator.py", line 994, in <module>
    sys.exit(main(sys.argv))
  File "C:\Users\leejenn1\work\Redfish\Redfish-Interop-Validator-required-profiles\RedfishInteropValidator.py", line 836, in main
    profiles = getProfiles(profile, './')
  File "C:\Users\leejenn1\work\Redfish\Redfish-Interop-Validator-required-profiles\commonProfile.py", line 109, in getProfiles
    filehandle = open(dirname + '/' + targetFile, "r")
FileNotFoundError: [Errno 2] No such file or directory: './/OCPBaselineHardwareManagement.v1_0_0.json'
…
```

According to Tomas’ comment, the tool does not look for any profile with version less than v1.0.0, so I changed the profile file name OCPBaselineHardwareManagement.v0_2_1.json to OCPBaselineHardwareManagement.v1_0_0.json and test again. Here is what I got:

```
INFO - ConfigURI: https://10.243.48.65
INFO - System Info: Test Config, place your own description of target system here
INFO - authtype: Basic,  cachefilepath: None,  cachemode: Off,  certificatebundle: None,  certificatecheck: False,  httpproxy: None,  
httpsproxy: None,  localonlymode: True,  logpath: ./logs,  metadatafilepath: ./SchemaFiles,  payloadfilepath: None,  payloadmode: Default,  
schemasuffix: _v1.xml,  servicemode: True,  timeout: 30,  username: root,  usessl: True,  warnrecommended: False,  

INFO - Start time: 06/25/18 - 13:46:01
DEBUG - Disallowed out of service URI
DEBUG - No such item RequiredProfiles
DEBUG - dont chkauth
DEBUG - callingResourceURI with authtype Basic and ssl True: /redfish/v1
DEBUG - 200, [200], {'Content-Security-Policy': "default-src self; connect-src 'self'; frame-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; object-src 'self'; img-src 'self'", 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-UA-Compatible': 'IE=11', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-store, no-cache', 'Pragma': 'no-cache', 'Content-Type': 'application/json', 'Content-Length': '752', 'Date': 'Tue, 12 May 2015 01:33:39 GMT', 'Server': 'lighttpd/1.4.45'},
TIME ELAPSED: 0.314625
…
```

But it seems to verify my system for all profile requirements.

**Comment by tomasg2012** [comment]
Should be implemented with latest PR.

**Comment by tomasg2012** [comment]
Closed with latest PR.
